version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test19021Project
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
- name: AbhiPackages
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
services:
- serviceName: project.test19021.integrations:log
  packages:
  - name: Test19021Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
